### ISSUE TITLE
Exercise 1

### ISSUE THREAD

**Issue by nighoge** [mak8427/Deep-Learning-Computer-Vision#1]
We need to correct my notebook and deciede on who is gonna present what part of it on Thursday.
The deadline for finetunig it oon oour part is Sunday evening

- [ ] Presentation
- [ ] Corecting the notebok

**Comment by nighoge** [comment]
I uploaded my corrected version oof the notebook.

**Comment by KhaledMadkour** [comment]
We can have the meeting on Sunday then because I will be out tomorrow all day, I will look at the notebook today too

**Comment by nighoge** [comment]
Scheduling a meeting sound lile a good idea. Sunday wirks for me as well

**Comment by KhaledMadkour** [comment]
Sunday anytime but 17 - 19:30 is fine by me

**Comment by nighoge** [comment]
Then i would suggest 4pm on discord

**Comment by mak8427** [comment]
For me it would be better at 3 pm

**Comment by nighoge** [comment]
Fine by me

**Comment by KhaledMadkour** [comment]
same

**Comment by nighoge** [comment]
Do you want to meet on discord? If yes, my name is till444
